//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.15 at 11:39:09 PM MSK 
//


package com.netcracker.sa.SOAP.methods;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the methods package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: methods
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemoveItemsRequest }
     * 
     */
    public RemoveItemsRequest createRemoveItemsRequest() {
        return new RemoveItemsRequest();
    }

    /**
     * Create an instance of {@link ArrayOfRemovedItems }
     * 
     */
    public ArrayOfRemovedItems createArrayOfRemovedItems() {
        return new ArrayOfRemovedItems();
    }

    /**
     * Create an instance of {@link SendItemsResponse }
     * 
     */
    public SendItemsResponse createSendItemsResponse() {
        return new SendItemsResponse();
    }

    /**
     * Create an instance of {@link RegistryMarketRequest }
     * 
     */
    public RegistryMarketRequest createRegistryMarketRequest() {
        return new RegistryMarketRequest();
    }

    /**
     * Create an instance of {@link ArrRegions }
     * 
     */
    public ArrRegions createArrRegions() {
        return new ArrRegions();
    }

    /**
     * Create an instance of {@link SendItemsRequest }
     * 
     */
    public SendItemsRequest createSendItemsRequest() {
        return new SendItemsRequest();
    }

    /**
     * Create an instance of {@link ArrayOfItems }
     * 
     */
    public ArrayOfItems createArrayOfItems() {
        return new ArrayOfItems();
    }

    /**
     * Create an instance of {@link UpdateItemsResponse }
     * 
     */
    public UpdateItemsResponse createUpdateItemsResponse() {
        return new UpdateItemsResponse();
    }

    /**
     * Create an instance of {@link RegistryMarketResponse }
     * 
     */
    public RegistryMarketResponse createRegistryMarketResponse() {
        return new RegistryMarketResponse();
    }

    /**
     * Create an instance of {@link RemoveItemsResponse }
     * 
     */
    public RemoveItemsResponse createRemoveItemsResponse() {
        return new RemoveItemsResponse();
    }

    /**
     * Create an instance of {@link GetLastUriRequest }
     * 
     */
    public GetLastUriRequest createGetLastUriRequest() {
        return new GetLastUriRequest();
    }

    /**
     * Create an instance of {@link RemoveRegionResponse }
     * 
     */
    public RemoveRegionResponse createRemoveRegionResponse() {
        return new RemoveRegionResponse();
    }

    /**
     * Create an instance of {@link AddRegionResponse }
     * 
     */
    public AddRegionResponse createAddRegionResponse() {
        return new AddRegionResponse();
    }

    /**
     * Create an instance of {@link AddRegionRequest }
     * 
     */
    public AddRegionRequest createAddRegionRequest() {
        return new AddRegionRequest();
    }

    /**
     * Create an instance of {@link UpdateItemsRequest }
     * 
     */
    public UpdateItemsRequest createUpdateItemsRequest() {
        return new UpdateItemsRequest();
    }

    /**
     * Create an instance of {@link ArrayOfUpdatedItems }
     * 
     */
    public ArrayOfUpdatedItems createArrayOfUpdatedItems() {
        return new ArrayOfUpdatedItems();
    }

    /**
     * Create an instance of {@link GetLastUriResponse }
     * 
     */
    public GetLastUriResponse createGetLastUriResponse() {
        return new GetLastUriResponse();
    }

    /**
     * Create an instance of {@link RemoveRegionRequest }
     * 
     */
    public RemoveRegionRequest createRemoveRegionRequest() {
        return new RemoveRegionRequest();
    }

    /**
     * Create an instance of {@link UpdatedItem }
     * 
     */
    public UpdatedItem createUpdatedItem() {
        return new UpdatedItem();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ArrayOfPhotos }
     * 
     */
    public ArrayOfPhotos createArrayOfPhotos() {
        return new ArrayOfPhotos();
    }

}
